import React, { useState } from 'react';
import { motion } from 'motion/react';
import {
  Sparkles,
  Calendar,
  Filter,
  ShieldAlert,
  Smile,
  Heart,
  Music,
  Trees,
  CheckCircle2,
  Copy,
  Check,
  Flower2,
} from 'lucide-react';
import { useApp } from '../../context/AppContext';
import { ActivityLog } from '../../types';

export const CaregiverActivityLog: React.FC = () => {
  const { state, setShowDisclaimerModal } = useApp();
  const logs: ActivityLog[] = state?.activityLogs || [];
  const [filterType, setFilterType] = useState<string>('all');
  const [copiedId, setCopiedId] = useState<string | null>(null);

  const filteredLogs = logs.filter((log) => {
    if (filterType === 'all') return true;
    return log.activity_type === filterType;
  });

  const handleCopyNote = (id: string, text: string) => {
    navigator.clipboard.writeText(text);
    setCopiedId(id);
    setTimeout(() => setCopiedId(null), 2000);
  };

  return (
    <div className="max-w-6xl mx-auto px-4 py-6 sm:py-8 space-y-8">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b-2 border-[#BFB5A2] dark:border-[#4A4F41] pb-6">
        <div>
          <h1 className="serif text-2xl sm:text-3xl font-black text-[#143513] dark:text-[#FFFFFF]">
            Activity Engagement Observations
          </h1>
          <p className="text-xs sm:text-sm text-[#121210] dark:text-[#F6F5EE] font-bold mt-1">
            Gentle narrative summaries generated by Gemini following each memory and cognitive session.
          </p>
        </div>

        {/* Filter Pills */}
        <div className="flex flex-wrap items-center gap-2">
          {['all', 'who_is_this', 'sounds_of_home', 'familiar_places', 'cognitive_exercises'].map((type) => (
            <button
              key={type}
              onClick={() => setFilterType(type)}
              className={`px-4 py-2 rounded-full text-xs font-black transition-all cursor-pointer ${
                filterType === type
                  ? 'bg-[#143513] text-white shadow-xs'
                  : 'bg-white dark:bg-[#1D1F1A] text-[#121210] dark:text-[#F6F5EE] border-2 border-[#BFB5A2] dark:border-[#4A4F41] hover:border-[#143513]'
              }`}
            >
              {type === 'all'
                ? 'All Activities'
                : type === 'cognitive_exercises'
                ? 'Cognitive Play'
                : type.replace(/_/g, ' ')}
            </button>
          ))}
        </div>
      </div>

      {/* Mandatory Non-Clinical Disclaimer Banner */}
      <div className="p-5 rounded-3xl bg-[#F8E7C6] dark:bg-[#423015] border-2 border-[#6E3B00] shadow-xs flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div className="flex items-start gap-3.5">
          <div className="w-10 h-10 rounded-xl bg-[#6E3B00] text-white flex items-center justify-center shrink-0 shadow-xs">
            <ShieldAlert className="w-6 h-6" />
          </div>
          <div>
            <h4 className="serif text-sm font-black text-[#6E3B00] dark:text-[#F7C04D] mb-0.5">
              Supportive Framing & Companion Notice
            </h4>
            <p className="text-xs text-[#542C00] dark:text-[#F8E7C6] font-bold leading-relaxed">
              These observations reflect shared family time, comfort, and engagement. They do not constitute medical records, cognitive scores, or clinical diagnostic evaluations.
            </p>
          </div>
        </div>
        <button
          onClick={() => setShowDisclaimerModal(true)}
          className="text-xs font-black text-[#6E3B00] dark:text-[#F7C04D] hover:underline whitespace-nowrap self-end sm:self-auto cursor-pointer"
        >
          View Notice Details →
        </button>
      </div>

      {/* Logs Timeline */}
      {filteredLogs.length === 0 ? (
        <div className="rounded-3xl bg-white dark:bg-[#1D1F1A] border-2 border-[#BFB5A2] dark:border-[#4A4F41] p-12 text-center text-[#121210] dark:text-[#F6F5EE]">
          <Smile className="w-12 h-12 text-[#143513] mx-auto mb-3" />
          <h3 className="serif text-lg font-black text-[#143513] dark:text-[#FFFFFF] mb-1">No Activity Logs Yet</h3>
          <p className="text-sm font-bold">
            When activities are completed in Patient Mode, Gemini will record warm observational notes here.
          </p>
        </div>
      ) : (
        <div className="space-y-4 sm:space-y-6">
          {filteredLogs.map((log) => {
            const dateFormatted = new Intl.DateTimeFormat('en-IN', {
              weekday: 'short',
              day: 'numeric',
              month: 'short',
              year: 'numeric',
              hour: '2-digit',
              minute: '2-digit',
            }).format(new Date(log.timestamp));

            return (
              <motion.div
                key={log.id}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                className="rounded-3xl bg-white dark:bg-[#1D1F1A] border-2 border-[#BFB5A2] dark:border-[#4A4F41] hover:border-[#143513] p-6 sm:p-7 shadow-md transition-all"
              >
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 border-b-2 border-[#BFB5A2] dark:border-[#4A4F41] pb-4 mb-4">
                  <div className="flex items-center gap-3">
                    <div className="p-2.5 rounded-xl bg-[#E0EDE0] dark:bg-[#263319] text-[#143513] dark:text-[#9BB858]">
                      {log.activity_type === 'who_is_this' ? (
                        <Heart className="w-5 h-5 text-[#7B1F13]" />
                      ) : log.activity_type === 'sounds_of_home' ? (
                        <Music className="w-5 h-5 text-[#1B6CA8]" />
                      ) : log.activity_type === 'cognitive_exercises' ? (
                        <Flower2 className="w-5 h-5 text-[#143513]" />
                      ) : (
                        <Trees className="w-5 h-5 text-[#6E3B00]" />
                      )}
                    </div>
                    <div>
                      <h3 className="serif text-base font-black text-[#000000] dark:text-[#FFFFFF] capitalize">
                        {log.activity_type === 'cognitive_exercises'
                          ? 'Cognitive & Memory Play'
                          : `${log.activity_type.replace(/_/g, ' ')} Activity`}
                      </h3>
                      <p className="text-xs text-[#121210] dark:text-[#F6F5EE] font-bold flex items-center gap-1">
                        <Calendar className="w-3.5 h-3.5 text-[#6E3B00]" />
                        {dateFormatted}
                      </p>
                    </div>
                  </div>

                  <div className="flex items-center gap-2">
                    <span className="px-3.5 py-1.5 rounded-full bg-[#E0EDE0] dark:bg-[#263319] text-[#143513] dark:text-[#9BB858] text-xs font-black border border-[#143513]/30">
                      {log.positive_count} of {log.total_count} engaged moments
                    </span>
                    <button
                      onClick={() => handleCopyNote(log.id, log.descriptive_note)}
                      className="p-2 rounded-full hover:bg-black/5 dark:hover:bg-white/5 text-[#121210] dark:text-[#F6F5EE] hover:text-[#000000] dark:hover:text-[#FFFFFF] transition-colors cursor-pointer"
                      title="Copy note"
                    >
                      {copiedId === log.id ? (
                        <Check className="w-4 h-4 text-[#143513] dark:text-[#9BB858]" />
                      ) : (
                        <Copy className="w-4 h-4" />
                      )}
                    </button>
                  </div>
                </div>

                <div className="text-base text-[#000000] dark:text-[#FFFFFF] leading-relaxed italic bg-[#F0EADF] dark:bg-[#272A22] p-4 sm:p-5 rounded-2xl border-2 border-[#BFB5A2] dark:border-[#4A4F41] font-bold">
                  "{log.descriptive_note}"
                </div>

                {log.details?.items_shown && log.details.items_shown.length > 0 && (
                  <div className="mt-4 flex flex-wrap items-center gap-2 text-xs text-[#121210] dark:text-[#F6F5EE]">
                    <span className="font-black">Exercises & Items:</span>
                    {log.details.items_shown.map((item, idx) => (
                      <span
                        key={idx}
                        className="px-3 py-1 rounded-full bg-[#F0EADF] dark:bg-[#272A22] text-[#000000] dark:text-[#FFFFFF] font-bold border border-[#BFB5A2] dark:border-[#4A4F41]"
                      >
                        {item}
                      </span>
                    ))}
                  </div>
                )}
              </motion.div>
            );
          })}
        </div>
      )}
    </div>
  );
};
